version: '3'
services:
  db:
    image: sparring-db
    environment:
      MYSQL_ROOT_PASSWORD: 'abstracta'
    volumes:
      - db-data:/var/lib/mysql
    ports:
    - 3308:3306
  web:
    image: sparring/sparring-web
    depends_on:
      - db
    ports:
      - 8080:8080
      - 8849:8849
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sparringdb
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=abstracta
  admin:
    image: sparring/sparring-admin
    ports:
      - 8081:8080

volumes:
  db-data: